import { useEffect, useState } from 'react';
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { CalendarDays, ChevronDown, CircleHelp } from 'lucide-react';
import { supabase } from '../lib/supabase';

const sources = ['Bing ads', 'Google ads', 'LinkedIn ads', 'Meta ads'];
const sourceColors = ['#0875b9', '#26a9db', '#5b2cb2', '#8d99aa'];
const spendData = [{ w: 'W1', Bing: 30, Google: 28, LinkedIn: 20, Meta: 35 }, { w: 'W2', Bing: 46, Google: 35, LinkedIn: 24, Meta: 29 }, { w: 'W3', Bing: 54, Google: 42, LinkedIn: 31, Meta: 40 }, { w: 'W4', Bing: 51, Google: 39, LinkedIn: 27, Meta: 35 }, { w: 'W5', Bing: 64, Google: 42, LinkedIn: 28, Meta: 36 }, { w: 'W6', Bing: 43, Google: 36, LinkedIn: 21, Meta: 33 }, { w: 'W7', Bing: 39, Google: 30, LinkedIn: 20, Meta: 27 }];
const cpcData = spendData.map((item, index) => ({ ...item, Bing: +(item.Bing / 105).toFixed(2), Google: +(item.Google / 110).toFixed(2), LinkedIn: +(item.LinkedIn / 76).toFixed(2), Meta: +(item.Meta / 112).toFixed(2), w: index % 2 ? '' : item.w }));
const channelData = [{ name: 'Google ads', value: 18 }, { name: 'Bing ads', value: 17 }, { name: 'LinkedIn ads', value: 16 }, { name: 'Snapchat ads', value: 15 }, { name: 'Facebook', value: 15 }, { name: 'TikTok', value: 15 }];

export default function Analytics() {
  const [loading, setLoading] = useState(true);
  const [totals, setTotals] = useState({ clicks: 0, impressions: 0, purchases: 0, revenue: 0, cost: 0, sessions: 0, users: 0 });
  useEffect(() => { void load(); }, []);
  const load = async () => { setLoading(true); const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { data } = await supabase.from('campaign_master_stats').select('*').eq('user_id', user.id); setTotals((data ?? []).reduce((sum: any, row: any) => ({ clicks: sum.clicks + Number(row.clicks || 0), impressions: sum.impressions + Number(row.impressions || 0), purchases: sum.purchases + Number(row.purchases || 0), revenue: sum.revenue + Number(row.revenue || 0), cost: sum.cost + Number(row.cost || 0), sessions: sum.sessions + Number(row.sessions || 0), users: sum.users + Number(row.users || 0) }), { clicks: 0, impressions: 0, purchases: 0, revenue: 0, cost: 0, sessions: 0, users: 0 })); setLoading(false); };
  const ctr = totals.impressions ? (totals.clicks / totals.impressions) * 100 : 0;
  const metrics = [
    ['Total users', compact(totals.users)], ['Sessions', compact(totals.sessions)], ['Avg engmt time', '00:00:44'], ['Purchase rate', totals.clicks ? `${((totals.purchases / totals.clicks) * 100).toFixed(2)}%` : '0.00%'], ['Purchases', compact(totals.purchases)], ['Clicks', compact(totals.clicks)], ['CTR', `${ctr.toFixed(2)}%`], ['CPM', totals.impressions ? ((totals.cost / totals.impressions) * 1000).toFixed(2) : '0.00'], ['CPC', totals.clicks ? (totals.cost / totals.clicks).toFixed(2) : '0.00'], ['ROAS', totals.cost ? `${((totals.revenue / totals.cost) * 100).toFixed(2)}%` : '0.00%']
  ];
  return <div className="analytics-shell -m-4 min-h-[calc(100vh-5rem)] bg-[#e8f1fb] p-3 md:-m-8 md:p-4">
    <div className="analytics-top"><div className="analytics-brand"><span className="analytics-mark">F</span><div><h1>Findora PPC Dashboard</h1><small>CAMPAIGN INTELLIGENCE</small></div></div><nav><button className="active">Overview</button><button>Dynamics</button></nav><button className="setup-button">Setup dashboard</button></div>
    <div className="analytics-grid"><section className="analytics-main"><div className="metric-grid">{metrics.map(([label, value], index) => <Metric key={label} label={label} value={loading ? '...' : value} tone={index % 5} />)}</div><div className="chart-grid"><Panel title="Traffic by channel"><div className="traffic-wrap"><ResponsiveContainer width="62%" height={170}><PieChart><Pie data={channelData} dataKey="value" innerRadius={42} outerRadius={67} paddingAngle={0}>{channelData.map((_, i) => <Cell key={i} fill={['#1a9fd6', '#0e669b', '#5f27b8', '#8293a3', '#ff696f', '#5ccc83'][i]} />)}</Pie></PieChart></ResponsiveContainer><div className="channel-labels">{channelData.map((item, i) => <span key={item.name}><i style={{ background: ['#1a9fd6', '#0e669b', '#5f27b8', '#8293a3', '#ff696f', '#5ccc83'][i] }} />{item.name}<b>{item.value}%</b></span>)}</div></div></Panel><Panel title="Weekly ad spend" legend><MiniBars data={spendData} stacked /></Panel><Panel title="Weekly CPC" legend><MiniBars data={cpcData} /></Panel></div><div className="table-grid"><DataTable title="Session source" rows={[['Bing ads', '703', '870', '429', '128', '18.21%'], ['Facebook', '654', '800', '419', '125', '19.11%'], ['Google ads', '339', '431', '234', '66', '19.47%'], ['Instagram', '0', '0', '0', '0', '-'], ['LinkedIn', '727', '909', '449', '124', '17.06%']]} headers={['Total users', 'Sessions', 'Engaged sessions', 'Purchases', 'Purchase rate']} /><DataTable title="Ad source" rows={sources.concat(['Snapchat ads', 'TikTok ads']).map((name, i) => [name, String(224 - i * 3), `${(67.4 - i * .8).toFixed(1)}K`, String(851 - i * 18), `0.${26 + (i % 2)}`, (3.32 + i * .04).toFixed(2), `${(1.26 - i * .03).toFixed(2)}%`])} headers={['Ad spend', 'Impressions', 'Clicks', 'CPC', 'CPM', 'CTR']} /></div></section><aside className="filter-panel"><div className="filter-title">Report date</div><div className="date-row"><span>3/8/2025 <CalendarDays size={12} /></span><span>5/7/2025 <CalendarDays size={12} /></span></div><div className="range"><i /><i /></div>{['Ad source', 'Ad campaign', 'Session source', 'Session campaign'].map(label => <label className="select-filter" key={label}>{label}<button>All <ChevronDown size={15} /></button></label>)}<div className="help-card"><div><b>Have questions?</b><a>Dashboard setup guide</a><a>Book a demo</a><a>Contact support</a></div><CircleHelp size={36} /></div></aside></div><div className="analytics-footer">Connect 70+ data sources with Findora</div>
  </div>;
}

function compact(value: number) { return value > 999 ? `${(value / 1000).toFixed(1)}K` : value.toLocaleString(); }
function Metric({ label, value, tone }: { label: string; value: string; tone: number }) { return <div className={`ppc-metric tone-${tone}`}><span>{label}</span><b>{value}</b></div>; }
function Panel({ title, legend, children }: { title: string; legend?: boolean; children: React.ReactNode }) { return <article className="ppc-panel"><h2>{title}</h2>{legend && <div className="chart-legend">{sources.map((source, i) => <span key={source}><i style={{ background: sourceColors[i] }} />{source}</span>)}</div>}{children}</article>; }
function MiniBars({ data, stacked = false }: { data: any[]; stacked?: boolean }) { return <ResponsiveContainer width="100%" height={130}><BarChart data={data} barGap={1}><XAxis dataKey="w" tick={{ fontSize: 9 }} axisLine={false} tickLine={false} /><YAxis width={22} tick={{ fontSize: 9 }} axisLine={false} tickLine={false} /><Tooltip /><Bar dataKey="Bing" fill={sourceColors[0]} stackId={stacked ? 'spend' : undefined} /><Bar dataKey="Google" fill={sourceColors[1]} stackId={stacked ? 'spend' : undefined} /><Bar dataKey="LinkedIn" fill={sourceColors[2]} stackId={stacked ? 'spend' : undefined} /><Bar dataKey="Meta" fill={sourceColors[3]} stackId={stacked ? 'spend' : undefined} /></BarChart></ResponsiveContainer>; }
function DataTable({ title, headers, rows }: { title: string; headers: string[]; rows: string[][] }) { return <article className="data-table"><div className="data-table-scroll"><table><thead><tr><th>{title}</th>{headers.map(header => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={row[0]}>{row.map((cell, n) => <td key={`${cell}-${n}`} className={n > 0 && n < row.length - 1 && i % 2 === 0 ? 'heat' : ''}>{n === 0 && <span className="expand">+</span>}{cell}</td>)}</tr>)}</tbody></table></div></article>; }
