import { useEffect, useState } from 'react';
import { Check, ChevronRight, CircleDollarSign, Copy, Globe2, Loader2, Plus, Tag, X } from 'lucide-react';
import { supabase } from '../lib/supabase';

type Campaign = { id: string; name: string; status: 'active' | 'paused' | 'pending'; daily_budget: number; keywords: string[] | null; target_audience: string | null; created_at: string; sites: { id: string; url: string; verified: boolean; verification_token: string | null } | null };
const emptyForm = { campaignName: '', siteUrl: '', dailyBudget: '', keywords: '', targetAudience: '' };

export default function CreateCampaign() {
  const [campaigns, setCampaigns] = useState<Campaign[]>([]);
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState(emptyForm);
  const [creating, setCreating] = useState(false);
  const [created, setCreated] = useState<Campaign | null>(null);
  const [copied, setCopied] = useState(false);

  const loadCampaigns = async () => {
    setLoading(true);
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return;
    const { data } = await supabase.from('campaigns').select('id, name, status, daily_budget, keywords, target_audience, created_at, sites(id, url, verified, verification_token)').eq('user_id', user.id).order('created_at', { ascending: false });
    setCampaigns((data as any) ?? []); setLoading(false);
  };
  useEffect(() => { void loadCampaigns(); }, []);
  const update = (field: keyof typeof emptyForm, value: string) => setForm(current => ({ ...current, [field]: value }));

  const createCampaign = async (event: React.FormEvent) => {
    event.preventDefault(); setCreating(true);
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) { setCreating(false); return; }
    const verifyToken = Math.random().toString(36).substring(2, 8).toUpperCase();
    const { data: site, error: siteError } = await supabase.from('sites').insert({ url: form.siteUrl, user_id: user.id, verified: false, verification_token: verifyToken }).select('id, url, verified, verification_token').single();
    if (siteError || !site) { alert('Unable to add your website. Please try again.'); setCreating(false); return; }
    const { data, error } = await supabase.from('campaigns').insert({ site_id: site.id, user_id: user.id, name: form.campaignName, daily_budget: Number(form.dailyBudget), keywords: form.keywords.split(',').map(item => item.trim()).filter(Boolean), target_audience: form.targetAudience || null, budget: 100, status: 'pending' }).select('id, name, status, daily_budget, keywords, target_audience, created_at').single();
    if (error || !data) { alert('Unable to create campaign. Please try again.'); setCreating(false); return; }
    const newCampaign = { ...data, sites: site } as Campaign;
    setCampaigns(current => [newCampaign, ...current]); setCreated(newCampaign); setForm(emptyForm); setShowForm(false); setCreating(false);
  };
  const copy = async (value: string) => { await navigator.clipboard.writeText(value); setCopied(true); setTimeout(() => setCopied(false), 2000); };

  return <div className="mx-auto max-w-6xl pb-8">
    <section className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#5d7567]">Campaign manager</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.045em] text-[#17211d]">Campaigns that find their people.</h1><p className="mt-2 text-sm text-[#758078]">Create, verify, and manage every destination from one place.</p></div><button onClick={() => { setCreated(null); setShowForm(true); }} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#173126] px-5 py-3 text-sm font-semibold text-white transition hover:bg-[#315f49]"><Plus size={18} /> Create campaign</button></section>
    {created && <section className="mt-7 rounded-2xl border border-[#cce5cf] bg-[#eff9f0] p-5"><div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#d9ff6c] text-[#173126]"><Check size={19} /></span><div className="flex-1"><h2 className="font-semibold">{created.name} is ready for verification</h2><p className="mt-1 text-sm text-[#47704d]">Add both snippets to the head of your destination website, then select Verify from the campaign list.</p><InstallSnippet label="1. Website verification" value={`<meta name="findora-verify" content="${created.sites?.verification_token}">`} copied={copied} onCopy={copy} /><InstallSnippet label="2. Findora tracking pixel" value={`<script src="${window.location.origin}/tracker.js" defer></script>`} copied={copied} onCopy={copy} /></div><button onClick={() => setCreated(null)} className="self-start text-[#47704d]"><X size={18} /></button></div></section>}
    <section className="mt-8 overflow-hidden rounded-2xl border border-[#e0e5de] bg-white"><div className="flex items-center justify-between border-b border-[#e9ece8] px-6 py-5"><div><h2 className="font-semibold text-[#17211d]">All campaigns</h2><p className="mt-1 text-sm text-[#78847c]">{campaigns.length} campaign{campaigns.length === 1 ? '' : 's'} in your workspace</p></div><span className="hidden rounded-full bg-[#e8f2e8] px-3 py-1.5 text-xs font-semibold text-[#315f49] sm:block">{campaigns.filter(item => item.status === 'active').length} active</span></div>{loading ? <div className="flex justify-center py-16 text-[#78847c]"><Loader2 className="animate-spin" /></div> : campaigns.length === 0 ? <Empty onCreate={() => setShowForm(true)} /> : <div className="divide-y divide-[#edf0eb]">{campaigns.map(campaign => <CampaignRow key={campaign.id} campaign={campaign} onVerified={loadCampaigns} />)}</div>}</section>
    {showForm && <CampaignModal form={form} update={update} creating={creating} onClose={() => setShowForm(false)} onSubmit={createCampaign} />}
  </div>;
}

function CampaignRow({ campaign, onVerified }: { campaign: Campaign; onVerified: () => Promise<void> }) { const [verifying, setVerifying] = useState(false); const verified = campaign.sites?.verified; const status = verified ? campaign.status : 'pending'; const verify = async () => { if (!campaign.sites) return; setVerifying(true); const { data: { session } } = await supabase.auth.getSession(); const response = await fetch('https://kdncxluglavhsygdxmio.supabase.co/functions/v1/verify-site', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${session?.access_token ?? ''}` }, body: JSON.stringify({ site_id: campaign.sites.id, url: campaign.sites.url, token: campaign.sites.verification_token, campaign_id: campaign.id }) }); const result = await response.json(); if (!response.ok) alert(result.message || 'Verification failed.'); else { alert(result.message); await onVerified(); } setVerifying(false); }; return <article className="flex flex-col gap-4 px-6 py-5 transition hover:bg-[#fbfcfa] sm:flex-row sm:items-center"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#e8f2e8] text-[#315f49]"><Globe2 size={20} /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-[#17211d]">{campaign.name}</h3><Status status={status} /></div><p className="mt-1 truncate text-sm text-[#78847c]">{campaign.sites?.url || 'Website pending'}</p><div className="mt-3 flex flex-wrap gap-1.5">{campaign.keywords?.slice(0, 4).map(item => <span key={item} className="rounded-full bg-[#f2f4f1] px-2 py-1 text-[11px] text-[#647268]">{item}</span>)}</div></div><div className="flex items-center justify-between gap-4 border-t border-[#edf0eb] pt-3 sm:border-0 sm:pt-0"><div><p className="text-xs text-[#849088]">Daily budget</p><p className="mt-1 flex items-center gap-1 font-semibold text-[#17211d]"><CircleDollarSign size={15} className="text-[#315f49]" />{Number(campaign.daily_budget).toFixed(2)}</p></div>{!verified ? <button onClick={() => void verify()} disabled={verifying} className="inline-flex items-center gap-1 rounded-lg bg-[#173126] px-3 py-2 text-xs font-semibold text-white disabled:opacity-60">{verifying && <Loader2 size={14} className="animate-spin" />} Verify</button> : <span className="inline-flex items-center gap-1 text-sm font-semibold text-[#315f49]">Live <ChevronRight size={16} /></span>}</div></article>; }
function InstallSnippet({ label, value, copied, onCopy }: { label: string; value: string; copied: boolean; onCopy: (value: string) => Promise<void> }) { return <div className="mt-4"><p className="text-xs font-semibold text-[#47704d]">{label}</p><div className="mt-2 flex flex-col gap-2 rounded-xl border border-[#cde0cf] bg-white p-3 sm:flex-row sm:items-center"><code className="flex-1 overflow-x-auto text-xs text-[#315f49]">{value}</code><button onClick={() => void onCopy(value)} className="inline-flex items-center justify-center gap-1 rounded-lg bg-[#173126] px-3 py-2 text-xs font-semibold text-white"><Copy size={14} /> {copied ? 'Copied' : 'Copy'}</button></div></div>; }
function Status({ status }: { status: string }) { const config = status === 'active' ? 'bg-[#e8f2e8] text-[#315f49]' : status === 'paused' ? 'bg-[#f2f3f1] text-[#667169]' : 'bg-[#fff3d9] text-[#936b24]'; return <span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold capitalize ${config}`}>{status === 'pending' ? 'Needs verification' : status}</span>; }
function Empty({ onCreate }: { onCreate: () => void }) { return <div className="px-6 py-16 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#e8f2e8] text-[#315f49]"><Tag size={21} /></span><h3 className="mt-4 font-semibold">Create your first campaign</h3><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-[#78847c]">Add a destination, budget, and the keywords that best describe what you offer.</p><button onClick={onCreate} className="mt-5 rounded-xl bg-[#173126] px-4 py-2.5 text-sm font-semibold text-white">Create campaign</button></div>; }
function CampaignModal({ form, update, creating, onClose, onSubmit }: { form: typeof emptyForm; update: (field: keyof typeof emptyForm, value: string) => void; creating: boolean; onClose: () => void; onSubmit: (event: React.FormEvent) => void }) { const fields: { key: keyof typeof emptyForm; label: string; placeholder: string; type?: string; hint?: string }[] = [{ key: 'campaignName', label: 'Campaign name', placeholder: 'Summer collection' }, { key: 'dailyBudget', label: 'Daily budget', placeholder: '50', type: 'number', hint: 'USD' }, { key: 'siteUrl', label: 'Destination website', placeholder: 'https://yourwebsite.com', type: 'url' }, { key: 'keywords', label: 'Target keywords', placeholder: 'fashion, linen, summer', hint: 'Separate with commas' }, { key: 'targetAudience', label: 'Target audience', placeholder: 'e.g. Style-conscious shoppers', hint: 'Optional' }]; return <div className="fixed inset-0 z-50 grid place-items-center bg-[#102019]/45 p-4 backdrop-blur-sm"><form onSubmit={onSubmit} className="w-full max-w-2xl rounded-3xl bg-white p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#5d7567]">New campaign</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em]">Set up your campaign</h2><p className="mt-2 text-sm text-[#78847c]">You can add as many campaigns as your business needs.</p></div><button type="button" onClick={onClose} className="rounded-full p-2 text-[#748078] hover:bg-[#f1f3f0]"><X size={19} /></button></div><div className="mt-7 grid gap-4 sm:grid-cols-2">{fields.map(field => <label key={field.key} className={field.key === 'siteUrl' ? 'sm:col-span-2' : ''}><span className="mb-2 flex justify-between text-sm font-semibold text-[#36463d]">{field.label}<em className="not-italic text-xs font-normal text-[#849088]">{field.hint}</em></span><input type={field.type || 'text'} required={field.key !== 'targetAudience' && field.key !== 'keywords'} min={field.key === 'dailyBudget' ? '1' : undefined} value={form[field.key]} onChange={event => update(field.key, event.target.value)} placeholder={field.placeholder} className="w-full rounded-xl border border-[#dce2db] px-3.5 py-3 text-sm outline-none transition placeholder:text-[#a1aaa3] focus:border-[#315f49] focus:ring-4 focus:ring-[#315f49]/10" /></label>)}</div><div className="mt-7 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-xl px-4 py-3 text-sm font-semibold text-[#667169]">Cancel</button><button type="submit" disabled={creating} className="inline-flex items-center gap-2 rounded-xl bg-[#173126] px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{creating && <Loader2 className="animate-spin" size={17} />} Create campaign</button></div></form></div>; }
